### ISSUE TITLE
Unversal solution

### ISSUE THREAD

**Issue by szepeviktor** [rmlewisuk/justdelete.me#362]
Please put something like this on the website:
e.g. in Adwords you cannot delete your account but:
"If there is a feature like user management, you can invite a fake identity to have admin privileges, than log in as fake and revoke permission from yourself."

Magyar nyelven: http://www.youtube.com/watch?v=ENbxInXWOYU
(if you understand Hungarian)

**Comment by szepeviktor** [comment]
Is it implemented?

**Comment by rmlewisuk** [comment]
Oops didn't mean to close this. Fixing now :)

**Comment by szepeviktor** [comment]
Actually it is *Adwords*.

**Comment by szepeviktor** [comment]
It was meant to be a universal solution for any account.

**Comment by rmlewisuk** [comment]
Oh I see what you mean now. I've made a note of this to add to the new design. Good suggestions, thanks.
