### ISSUE TITLE
Paypal deletion is NOT easy

### ISSUE THREAD

**Issue by ghost** [rmlewisuk/justdelete.me#464]
Change it to "Cannot be fully deleted without contacting customer-services"(red).

Newly create an account with no credit card will be locked by PayPal.
It's impossible without contacting PayPal by *phone* to delete it.

**Comment by Cattze2015** [comment]
Also, they never delete your information. You can confirm what I'm saying by calling them directly.

They simply close your account with everything inside(your personal information).
I'm surprised to notice that they still hold my old accounts(over several years ago).

Paypal should not be green. This is not a "delete".
