### ISSUE TITLE
Feature Request: Retina Support

### ISSUE THREAD

**Issue by vinkla** [rmlewisuk/justdelete.me#467]
Adding retina support to the extension domain field icons. It will be a lot appreciated.

![none-retina](https://cloud.githubusercontent.com/assets/499192/5797881/7c968b38-9fc1-11e4-9dc7-05d7e4c68e1e.png)

**Comment by rmlewisuk** [comment]
The Chrome extension is maintained here: https://github.com/MikeRogers0/justdelete.me-chrome-extension
