### ISSUE TITLE
SmartRecruiters appears glitched

### ISSUE THREAD

**Issue by jackmawer** [rmlewisuk/justdelete.me#527]
Hello!

I'm running Windows 10, Mozilla Firefox Developer Edition 41.0a2 (2015-07-30) (Aurora update channel) and I experienced a graphical glitch upon scrolling to the SmartRecruiters section while browsing the main page.
The section of the website:
![The section of the Website](http://i.gyazo.com/f8574ff3f925c842f5d6cdd2dba99a0d.png)
Closeup of the graphical glitch:
![Closeup of the Graphical Glitch](http://i.gyazo.com/2d63b6d7e41b86fd80c7f6d4ae7e3ea3.png)

Thanks,
Jack

**Comment by rmlewisuk** [comment]
Thanks, fixed. (Should show up on the site soon)
