### ISSUE TITLE
Don't link to diasp.eu node for the diaspora* project

### ISSUE THREAD

**Issue by Flaburgan** [rmlewisuk/justdelete.me#529]
diaspora* is a decentralized network. Currently, the page links to [diasp.eu](https://github.com/rmlewisuk/justdelete.me/search?utf8=%E2%9C%93&q=diasp.eu) which is one of the [hundreds installations](http://podupti.me) of diaspora\*. I guess the site should link to the [official website](https://diasporafoundation.org) of diaspora* instead, explaining how to delete an account. Do you want me to open a PR?

**Comment by rmlewisuk** [comment]
I've updated the name instead (to show its actually for diasp.eu).

Thanks :+1:

**Comment by Flaburgan** [comment]
Well the process and even the end of the url (```/user/edit#close_account_pane```) is true for every diaspora* nodes (and diasp.eu is only [one of them](http://podupti.me/)). I think it will be nice to keep the name "diaspora*".
