### ISSUE TITLE
Error on the live site , Smartrecruiters

### ISSUE THREAD

**Issue by szepeviktor** [rmlewisuk/justdelete.me#534]
Notice: Undefined variable: difficulty_difficult in /Users/rmlewisuk/Sites/personal/jdm/dev.php(134) : eval()'d code on line 1

Call Stack:
    0.0003     237984   1. {main}() /Users/rmlewisuk/Sites/personal/jdm/static-gen.php:0
    0.0031     775136   2. include('/Users/rmlewisuk/Sites/personal/jdm/dev.php') /Users/rmlewisuk/Sites/personal/jdm/static-gen.php:97
    0.0284    2050312   3. eval('return $difficulty_difficult;') /Users/rmlewisuk/Sites/personal/jdm/dev.php:134

**Comment by rmlewisuk** [comment]
Fixed.

**Comment by szepeviktor** [comment]
You can set up a build rule to detect these.
for example `grep -i "Call Stack:"`.

**Comment by rmlewisuk** [comment]
I'm moving to a new build system, so it will catch these. Thanks.
