### ISSUE TITLE
Can notes include newlines, links or any text formatting?

### ISSUE THREAD

**Issue by neeklamy** [rmlewisuk/justdelete.me#540]
I would guess it’s okay to include newlines in the notes field.

But how about links? And is there any text formatting allowed?

Thanks

**Comment by rmlewisuk** [comment]
We *can* include links but it's probably best not to. What is it you wanted to add as a link?

**Comment by neeklamy** [comment]
I was mostly interested in adding newlines to suggest making the notes a bit more readable for DeviantArt. Thought I’d ask about text formatting and links whilst I was here.

**Comment by rmlewisuk** [comment]
For the moment, new lines are good but try to avoid other formatting.

**Comment by neeklamy** [comment]
Thanks, but how do we include newlines `\n` or something else?
