### ISSUE TITLE
What to classify the difficulty as when it isn’t so straightforward?

### ISSUE THREAD

**Issue by neeklamy** [rmlewisuk/justdelete.me#545]
>Go to "Profile settings", scroll down, and click "Delete profile." Your profile will be deleted on all platforms in the Startnext Network, and you will no longer receive messages from the site. Please note that this action cannot be undone.

>**It may be that you cannot delete your profile** for the following reasons: 
>  - You have a project in the starting phase, funding phase, or end phase (the payout).
>  - You have an active crowdfunding page.
>  - You have supported a project that is still in the funding phase, and we have not yet received your payment or your payment has not yet been returned to you.

From [Startnext FAQ: How can I delete my profile?](https://www.startnext.com/hilfe/FAQ.html#q74)

So, depending on the state of an account, it’s easy *or* (currently) impossible to delete an account. How would this be classified?

An easy (ha!) hack would be to just list the site twice. Or perhaps adding a new difficulty level (which could then be localised and used on other listings).

**Comment by rmlewisuk** [comment]
I think in this scenario, it should still be listed as easy because the reasons you cannot delete are complete reasonable — it's basically saying if you're using the site for it's main purpose, you can't delete which makes sense.
