### ISSUE TITLE
Feature Request: Data retention policy

### ISSUE THREAD

**Issue by MrTimscampi** [rmlewisuk/justdelete.me#553]
It would be nice to have a field (or fields) that shows if and what information about the user are kept after deleting the account.

**Comment by rmlewisuk** [comment]
That's is beyond the scope of what justdelete.me can do. However, I would recommend checking out https://tosdr.org/ for that kind of information.

**Comment by neeklamy** [comment]
It looks like it would be possible to have a browser extension that uses the [ToS;DR API](https://tosdr.org/api.html) and brings the two services together.
