### ISSUE TITLE
Update js bin info

### ISSUE THREAD

**Issue by remy** [rmlewisuk/justdelete.me#608]
It currently says "hard". 

As of (about 6-9 months ago) this was changed:

<img width="1167" alt="screen shot 2016-01-29 at 17 51 19" src="https://cloud.githubusercontent.com/assets/13700/12683403/f775165a-c6b0-11e5-8253-4ddc3df2b6e1.png">

I had a user come through from your site today asking for their account to be deleted, so asking if you can update the info on this site.

Thanks.

**Comment by neeklamy** [comment]
I’ve pushed PR #610 to fix this.

**Comment by rmlewisuk** [comment]
PR is now merged and live. Thanks 👍
